### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [NA] Bumped the build number (if the version is unchanged)
* [NA] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raybellwaves** [comment]
Failing with

`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'azure-identity'}`

`https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=192161&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=472`

Need to add [`azure-identity`](https://pypi.org/project/azure-identity/) to conda-forge. https://github.com/conda-forge/azure-identity-feedstock gives 404.

**Comment by raybellwaves** [comment]
@conda-forge-admin please rerender

**Comment by raybellwaves** [comment]
@conda-forge-admin please rerender

**Comment by raybellwaves** [comment]
@conda-forge-admin please rerender

**Comment by raybellwaves** [comment]
Not sure what's going on here
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=192759&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=478
`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'azure-identity'}`

https://github.com/conda-forge/azure-identity-feedstock is up

**Comment by martindurant** [comment]
ping conda forge help? I see https://anaconda.org/conda-forge/azure-identity/files

**Comment by marcelotrevisani** [comment]
I add this package yesterday I think
so it will be available now

**Comment by marcelotrevisani** [comment]
Next time please use a fork @raybellwaves

**Comment by marcelotrevisani** [comment]
Please see
https://github.com/conda-forge/adlfs-feedstock#updating-adlfs-feedstock
https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=maintaining#forking-and-pull-requests

**Comment by raybellwaves** [comment]
My apologies @marcelotrevisani

**Pull request merged**
